### PR TITLE
Change to copy full URI

### PR DESCRIPTION
**Pull request by JohnVeness**
Copy the full URI, not just what was in the href.

Ref: https://stackoverflow.com/questions/2639070/get-the-full-uri-from-the-href-property-of-a-link

### CODE REVIEW

**Comment by cjamin** [comment]
@DanKaplanSES Please integrate this pull-request, it really improves the add-on!
Thanks!

**Comment by DanKaplanSES** [comment]
This looks good. Thank you for contributing! I didn't know anyone used this but me. :)

**Comment by DanKaplanSES** [comment]
Although I've merged this, I haven't released the change because I'm unable to log into mozilla.org right now. I keep getting stuck in this loop for setting up 2 factor auth.

**Comment by cjamin** [comment]
@DanKaplanSES Is the current version available on mozilla.org the latest version? I installed it but it does not seem to work at all: Alt + left click does not copy anything. Should I restart Firefox or similar?

**Comment by DanKaplanSES** [comment]
> @DanKaplanSES Is the current version available on mozilla.org the latest version? I installed it but it does not seem to work at all: Alt + left click does not copy anything. Should I restart Firefox or similar?

I believe it is because it says it was updated a month ago. `alt + left click` works for me. What website are you trying this on and which element are you clicking?

**Comment by cjamin** [comment]
Ok, it seems to be working now. Probably needed to restart Firefox.
It is not working when the website is catching the onclick mouse event, though.

**Pull request merged**
